### ISSUE TITLE
src-cli: Provide better stats/numbers while running a campaign

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#15607]
From a customer:

> When the local run is done, make stats on run times available

> Show current progress in numbers and not only a progress bar.

**Comment by rrhyne** [comment]
A customer requested we show the count of repositories where no changesets were produced. In addition to the stats, a list of these repositories would be helpful to display to the user.

Use case:

I need to update all repositories that use a certain library. I run a search and find 100 repositories. I create a campaign to make the update and run it. Only 98 changesets are created. I need to know which two repositories were not updated so I can determine why.


Use case:

I have a list of repositories to edit and create a campaign using multiple on: \n\t repository: statements. Several repositories were not changed and I need to know which ones were not altered.

**Comment by rrhyne** [comment]
Have we thought about storing this information with the campaign? This could be a core requirement for users who need to track where changes were applied.

- User creates spec using **repository:** statements to specifically define a set of 100 repositories
- User applies a campaign. 20 merge requests are successfully merged, 10 have errors, 70 are in progress
- User updates campaign to correct issues with the errored repositories and re-applies the campaign
- The UI now shows only 80 changesets 
- The user needs to know which of the 20 were fixed, but cannot tell from the UI

**Comment by mrnugget** [comment]
> A customer requested we show the count of repositories where no changesets were produced. In addition to the stats, a list of these repositories would be helpful to display to the user.

Count make sense. I'll try to think of something. The list already exists if they run it with `-v`.

> Have we thought about storing this information with the campaign? This could be a core requirement for users who need to track where changes were applied. [...]

What you describe here is about how we keep track of the lifecycle of changesets on the server. That's what we talked about last week: a "timeline" to show which changesets were attached, which ones were detached, etc. Combine that with the better delta API and that problem should if not solved be much smaller.

Since this ticket is about src-cli and providing better information about a current run, I think we should move further discussion of that into a separate ticket.
