### ISSUE TITLE
src batch: unknown subcommand "exec"

### ISSUE THREAD

**Issue by NiklasRosenstein** [sourcegraph/sourcegraph#37559]
- **Sourcegraph version:** 3.41.0
- **Platform information:** Running on Docker (Engine v20.10.12) on Ubuntu 20.04, Ignite v0.10.0, Git 2.25.1, src-cli version 3.41.0

#### Steps to reproduce:

1. Setup `sourcegraph/server:3.41.0` to run via Docker Compose [1]
2. Follow the steps to manually deploy the executor binaries ([link to docs](https://docs.sourcegraph.com/@3.41/admin/deploy_executors#binaries))
3. Try to run a batch change [2] pipeline using the executor

[1]

```docker-compose.yml
version: '3.4'
services:
  sourcegraph:
    image: sourcegraph/server:3.41.0
    ports: [ "80:7080" ]
    volumes: [ "./var/conf:/etc/sourcegraph", "sourcegraph_data:/var/opt/sourcegraph" ]
    restart: unless-stopped

volumes:
  sourcegraph_data:
```

[2]

```yml
name: migrate_to_artifactory_token
description: Add Hello World to READMEs

# This is your query from search
on:
  - repositoriesMatchingQuery: context:global repo:niklas.rosenstein/sg-test
steps:
  - run: ls
    container: ubuntu:18.04

# Describe the changeset (e.g., GitHub pull request) you want for each repository.
changesetTemplate:
  title: Hello World
  body: My first batch change!
  branch: hello-world # Push the commit to this branch.
  commit:
    message: Append Hello World to all README.md files
```

#### Expected behavior:

The execution runs successfully.

#### Actual behavior:

The execution fails with `src batch: unknown subcommand "exec"`

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1318438/175066798-4c981292-abc8-49a2-959b-095b4a3fee04.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1318438/175067021-7a0b2cc7-4a31-4ad5-bba5-e0f1b883d039.png">

Executor logs:

```
{"SeverityText":"DEBUG","Timestamp":1655910452038005197,"InstrumentationScope":"executor","Caller":"executor/main.go:49","Function":"main.main","Body":"logger.scoped","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"scope":{"name":"executor","desc":"the executor service polls the public frontend API for work to perform"}}
{"SeverityText":"DEBUG","Timestamp":1655910452038207207,"InstrumentationScope":"service","Caller":"executor/main.go:58","Function":"main.main","Body":"logger.scoped","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"scope":{"name":"service","desc":"executor service"}}
{"SeverityText":"INFO","Timestamp":1655910452160604386,"InstrumentationScope":"executor","Caller":"executor/main.go:76","Function":"main.main","Body":"Telemetry information gathered","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"info":"{OS:linux Architecture:amd64 DockerVersion:20.10.12 ExecutorVersion:155933_2022-06-22_a9e2810c52aa GitVersion:2.25.1 IgniteVersion:v0.10.0 SrcCliVersion:3.41.0}"}}
{"SeverityText":"DEBUG","Timestamp":1655910452160659989,"InstrumentationScope":"executor_processor","Caller":"executor/main.go:115","Function":"main.makeWorkerMetrics","Body":"logger.scoped","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"scope":{"name":"executor_processor","desc":"executor worker processor"}}
t=2022-06-22T15:07:32+0000 lvl=info msg="Connecting to Sourcegraph instance" url=http://my-sourcegraph-instance.com
t=2022-06-22T15:07:32+0000 lvl=info msg="Connected to Sourcegraph instance"
{"SeverityText":"INFO","Timestamp":1655910452649632675,"InstrumentationScope":"executor_processor","Caller":"workerutil/worker.go:298","Function":"github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle","Body":"Dequeued record for processing","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"name":"executor_batches_worker","id":146}}
{"SeverityText":"INFO","Timestamp":1655910452649753981,"InstrumentationScope":"executor_processor.worker.Handle","Caller":"worker/handler.go:100","Function":"github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/worker.(*handler).Handle","Body":"Creating workspace","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"handle":{"jobID":146,"repositoryName":"my-gitlab-instance.com/niklas.rosenstein/sg-test","commit":"2581a401908bcb898b8995faefc74bb21da5dcf1"}}}
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository init"
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository remote add origin http://executor@my-sourcegraph-instance.com/.executors/git/my-gitlab-instance.com/niklas.rosenstein/sg-test"
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=1 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=1 key=setup.git.init outLen=77 exitCode=0xc00011a970 durationMs=0xc00011a978
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository config --local gc.auto 0"
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository -c protocol.version=2 -c http.extraHeader=Authorization: token-executor REDACTED -c http.extraHeader=X-Sourcegraph-Actor-UID: internal fetch --progress --no-recurse-submodules --no-tags --depth=1 origin 2581a401908bcb898b8995faefc74bb21da5dcf1"
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=2 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=2 key=setup.git.add-remote outLen=0 exitCode=0xc0002974d8 durationMs=0xc000297500
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=3 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=4 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository checkout --progress --force 2581a401908bcb898b8995faefc74bb21da5dcf1"
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=4 key=setup.git.fetch outLen=5388 exitCode=0xc00011acb8 durationMs=0xc00011acc0
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=5 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: git -C /tmp/1014079631/repository remote set-url origin my-gitlab-instance.com/niklas.rosenstein/sg-test"
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=5 key=setup.git.checkout outLen=761 exitCode=0xc00011acc8 durationMs=0xc00011ad70
{"SeverityText":"INFO","Timestamp":1655910452772908898,"InstrumentationScope":"executor_processor.worker.Handle","Caller":"worker/handler.go:178","Function":"github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/worker.(*handler).Handle","Body":"Setting up VM","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"handle":{"jobID":146,"repositoryName":"my-gitlab-instance.com/niklas.rosenstein/sg-test","commit":"2581a401908bcb898b8995faefc74bb21da5dcf1"}}}
t=2022-06-22T15:07:32+0000 lvl=info msg="Running command: ignite run --runtime docker --network-plugin cni --cpus 4 --memory 12G --size 20G --copy-files /tmp/1014079631:/work --ssh --name executor-45b0fa65-e8a6-497d-a968-c2aa2463cb4b sourcegraph/ignite-ubuntu:insiders"
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=6 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=6 key=setup.git.set-remote outLen=0 exitCode=0xc00011ad78 durationMs=0xc00011ae10
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=7 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=8 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:32+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=9 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:36+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=9 key=setup.firecracker.start outLen=152
t=2022-06-22T15:07:37+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=9 key=setup.firecracker.start outLen=427
t=2022-06-22T15:07:38+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=9 key=setup.firecracker.start outLen=533
{"SeverityText":"INFO","Timestamp":1655910469119436909,"InstrumentationScope":"executor_processor.worker.Handle","Caller":"worker/handler.go:213","Function":"github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/worker.(*handler).Handle","Body":"Running src-cli step #0","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"handle":{"jobID":146,"repositoryName":"my-gitlab-instance.com/niklas.rosenstein/sg-test","commit":"2581a401908bcb898b8995faefc74bb21da5dcf1"}}}
t=2022-06-22T15:07:49+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=9 key=setup.firecracker.start outLen=533 exitCode=0xc0003dac90 durationMs=0xc0003dac98
t=2022-06-22T15:07:49+0000 lvl=info msg="Running command: ignite exec executor-45b0fa65-e8a6-497d-a968-c2aa2463cb4b -- cd /work && SRC_ENDPOINT=http://this-will-never-exist-i-hope src batch exec -f input.json -repo repository -cache cache -tmp .src-tmp -sourcegraphVersion 3.41.0"
t=2022-06-22T15:07:49+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=10 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
{"SeverityText":"ERROR","Timestamp":1655910471457046820,"InstrumentationScope":"service.apiworker.exec","Caller":"command/run.go:91","Function":"github.com/sourcegraph/sourcegraph/enterprise/cmd/executor/internal/command.runCommand","Body":"operation.error","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"count":1,"elapsed":2.337506106,"error":"command failed"}}
t=2022-06-22T15:07:51+0000 lvl=info msg="Running command: ignite rm -f executor-45b0fa65-e8a6-497d-a968-c2aa2463cb4b"
t=2022-06-22T15:07:51+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=10 key=step.src.0 outLen=170 exitCode=0xc00044a298 durationMs=0xc00044a2a0
t=2022-06-22T15:07:51+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=11 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:52+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=11 key=teardown.firecracker.remove outLen=330 exitCode=0xc00044a480 durationMs=0xc00044a488
t=2022-06-22T15:07:52+0000 lvl=dbug msg="Writing log entry" jobID=146 entryID=12 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1
t=2022-06-22T15:07:52+0000 lvl=dbug msg="Updating executor log entry" jobID=146 repositoryName=my-gitlab-instance.com/niklas.rosenstein/sg-test commit=2581a401908bcb898b8995faefc74bb21da5dcf1 entryID=12 key=teardown.fs outLen=25 exitCode=0xc00044b0f0 durationMs=0xc00044b0f8
{"SeverityText":"WARN","Timestamp":1655910472486867955,"InstrumentationScope":"executor_processor.worker.Handle","Caller":"workerutil/worker.go:372","Function":"github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).handle","Body":"Marked record as errored","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{"error":"failed to perform src-cli step: command failed"}}
{"SeverityText":"DEBUG","Timestamp":1655910472487221574,"InstrumentationScope":"executor_processor.worker.Handle","Caller":"workerutil/worker.go:382","Function":"github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).handle","Body":"Handled record","Resource":{"service.name":"executor","service.version":"155933_2022-06-22_a9e2810c52aa","service.instance.id":"infra-sourcegraph"},"Attributes":{}}
```

**Comment by eseliger** [comment]
Hello! 

When running step 3 of the guide 

> Step 3: Generate Ignite base image

Did you make sure to replace the version string by 3.41.0? 

This is not clear from the docs at all I realize so if that’s it let me update the docs 😅
if not let me know and we can debug further!

**Comment by eseliger** [comment]
Also, `src batch -h` doesn't print that command because it's an internal-only thing, that should eventually disappear but for now that's how we make the sausage :) `src batch exec -h` should still print a help text for you.

**Comment by NiklasRosenstein** [comment]
Hey @eseliger! Thanks for the quick reply.

I did not look to update the version number in the command. In the docs it says 3.41.1, so if I did everything right I should only be 1 patch removed from the one expected by my sourcegraph instance?

But it turns out that I did not do everything right, now that I look closer and try to rerun it again with 3.41.0! This URL does not exist so the whole command doesn't really work. I must have missed that it didn't work when I followed the steps.


https://raw.githubusercontent.com/sourcegraph/sourcegraph/main/enterprise/cmd/executor/image/ignite-ubuntu/Dockerfile

**Comment by eseliger** [comment]
you're right :( I will fix that right away!

**Comment by eseliger** [comment]
Duh :( for visibility, I fixed the link here: https://github.com/sourcegraph/sourcegraph/pull/37645

For step 3 of the guide: https://docs.sourcegraph.com/@3.41/admin/deploy_executors#binaries:~:text=Step%203%3A%20Generate%20Ignite%20base%20image
did you make sure to set `export SRC_CLI_VERSION="3.41.0"` instead? This is the current latest version. Sorry the docs don't auto reflect the latest version in there. 
To finally test the image, can you run `docker run --rm sourcegraph/ignite-ubuntu:insiders src version` and check if it prints 3.41.0?

**Comment by malomarrec** [comment]
@NiklasRosenstein thanks for this report. @eseliger is off, @BolajiOlajide will take this over

Besides, just a friendly note on the way our pricing work: Batch Changes is a [paying feature](https://about.sourcegraph.com/pricing) of Sourcegraph. In the Sourcegraph Enterprise / Free plan, batch changes are limited to 5 changeset max.
Given server-side is in Beta, the gate is not enforced _just yet_, but it will come in the following releases, so just a friendly heads up :)

**Comment by NiklasRosenstein** [comment]
Thanks for the heads-up @malomarrec !

**Comment by BolajiOlajide** [comment]
Hello @NiklasRosenstein 

I just went through the thread with Erik - I'll be taking over as Erik is off.

> I've retried step 3 once more and still could not get it to work, even though the docker run command you posted returned the expected version.

Can you share the error message received? I see the linked above is still showing the wrong link to download the Dockerfile, [here's the correct one](https://docs.sourcegraph.com/admin/deploy_executors#binaries:~:text=Step%203%3A%20Generate%20Ignite%20base%20image).

> It seems that if you don't have the sourcegraph/ignite-ubuntu:insiders image, the Sourcegraph executor will just create one for you and it works.
Yes, if the image doesn't exist locally, it'll pull from docker hub, however this might not contain the correct version.

```sh
export EXECUTOR_FIRECRACKER_IMAGE="sourcegraph/ignite-ubuntu:insiders"

# Download Dockerfile and build Docker image
mkdir -p /tmp/ignite-ubuntu
curl -sfLo /tmp/ignite-ubuntu/Dockerfile https://raw.githubusercontent.com/sourcegraph/sourcegraph/main/enterprise/cmd/executor/vm-image/ignite-ubuntu/Dockerfile
docker build -t "${EXECUTOR_FIRECRACKER_IMAGE}" --build-arg SRC_CLI_VERSION="${SRC_CLI_VERSION}" /tmp/ignite-ubuntu
```

The step above ensures you build the correct image with the version of `src-cli` supported.

Can you clarify if you've been able to get it working and if not what step are you at so I can guide you accordingly.
