### ISSUE TITLE
compute: Compute output command does not respect `case`

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37972]
Sometimes it seems we get an empty Value field in a compute replacement, even when the replacement is a static string. Example:

```
fork:yes archived:yes lang:go count:99999999 content:output(historical -> yayaya) repo:^(github\.com/sourcegraph/sourcegraph)$
```

As I understand, this should result in every match being replaced with `yayaya`. Instead, some of the results are all empty `Value`.

```
event: results
data: [{"value":"yayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"}]

event: progress
data: {"done":false,"matchCount":0,"durationMs":39,"skipped":[]}

event: results
data: [{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\nyayaya\nyayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\nyayaya\nyayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\nyayaya\nyayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"yayaya\n","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"}]

event: progress
data: {"done":false,"matchCount":0,"durationMs":103,"skipped":[]}

// This is the notable section
event: results
data: [{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"},{"value":"","kind":"output","repositoryID":11,"repository":"github.com/sourcegraph/sourcegraph"}]

event: progress
data: {"done":false,"matchCount":0,"durationMs":125,"skipped":[]}

event: progress
data: {"done":true,"matchCount":0,"durationMs":125,"skipped":[]}

event: done
data: {}
```

/cc @benvenker @lguychard

**Comment by coury-clark** [comment]
cc @rvantonder when you get a chance

**Comment by coury-clark** [comment]
I just saw this: https://github.com/sourcegraph/sourcegraph/pull/38061/files#diff-c4b099933ca87edc654cdd31e85a0cfa92f48929c26f94a88f837730a3d9ce31R108-R112

Is this intentional, and under the hood these correspond to matches that aren't FileMatch? I don't fully understand whats going on here but this stuck out to me.

**Comment by rvantonder** [comment]
This logic only affects semantics of queries with a `select:` value, so it's unrelated. To understand what's going with that there's https://github.com/sourcegraph/sourcegraph/pull/34677

**Comment by rvantonder** [comment]
this is an issue with case sensitivity. `historical` is searched case-insensitively and the `output` command checks that that string matches a case-sensitive result. when it doesn't (sees `Historical` instead of `historical`) then you seen an empty value.

this is similar to the divergent behavior on the `Match_context` result a long time ago. I didn't bring the "fix" to `output` because I'm not sure I actually like having the input pattern treated case-insensitive by default for compute. I know for Code Insights you want to be in lockstep with search, but I actually think the case-insensitive default is harmful for code insights or code statistics (with no real data to back that up, but OK).

Either way, there's is a bug here because using `case:yes` versus `case:no` makes no difference, and it should honor that. I will look into a fix next week. I'm hesitant to make the default case-insensitive on the pattern, but I will probably lean to keep it in line with search despite the nagging feeling that I don't like this, since the client can force `case:yes` anyway.

**Comment by felixfbecker** [comment]
> Either way, there's is a bug here because using case:yes versus case:no makes no difference, and it should honor that. I will look into a fix next week.

Curious, was this fixed? Tried digging through [PRs related to `compute` and `case`](Either way, there's is a bug here because using case:yes versus case:no makes no difference, and it should honor that. I will look into a fix next week.), apologies if I missed it

**Comment by felixfbecker** [comment]
Ah I think it was fixed: https://github.com/sourcegraph/sourcegraph/issues/29932

**Comment by felixfbecker** [comment]
@coury-clark should this issue be closed?

**Comment by coury-clark** [comment]
@felixfbecker Not to my knowledge in the `output` command. The linked PR above was for the `match_only` command.

**Comment by rvantonder** [comment]
confirmed not fixed yet! had a branch to for [failling test case](https://github.com/sourcegraph/sourcegraph/commit/b8fb149ec1f7ab26dbd97038bba36d94dcae5c75#diff-b685998e1ecdb49c6f571cff42f6b75bbc404ca9877d2c78a6350e574b19f432) self-assinging, will put this in my queue somehwere

**Comment by camdencheek** [comment]
Closing since we have essentially abandoned compute.
