### ISSUE TITLE
Open Source Plan

### ISSUE THREAD

**Issue by naturalwarren** [sourcegraph/sourcegraph#6709]
#### Question Description

Are there instructions for building the [open source plan](https://about.sourcegraph.com/pricing/) of Sourcegraph? I'd like to build a Docker image of it.

From what I can discern there's two paths here:

1. Build the server image from source using `enterprise/cmd/server` as a guide. This would require some minor forking in order to avoid using enterprise code. However, based on the [Build Notes](https://github.com/sourcegraph/sourcegraph/tree/master/enterprise) it doesn't appear to be possible to build the server image from source; `https://github.com/sourcegraph/dev-private` is not accessible.  The [server image](https://hub.docker.com/r/sourcegraph/server/) hosted on DockerHub can't be built from the source code in this repository. 

2. Build my own docker image that fires up `dev/launch.sh`. This seems less than ideal since I'd need to run Docker in Docker for the script to work out of the box. At the moment my container bombs out with the following output because I'm not:

```bash
01:10:55               keycloak | Not using Keycloak. Only runs in enterprise mode.
01:10:55               keycloak | Terminating keycloak
01:10:55                symbols | Building /sourcegraph/libsqlite3-pcre.so...
01:10:55        zoekt-webserver | 2019/11/20 01:10:55 listening on :3070
01:10:55                  watch | Using chokidar.
01:10:55                docsite | # Doc site is available at http://localhost:5080
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/.exrc
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/.gear-rules
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/Makefile
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/pcre.c
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/readme.txt
01:10:56                symbols | sqlite3-pcre-c98da412b431edb4db22d3245c99e6c198d49f7a/sqlite3-pcre.spec
01:10:56                symbols | /tmp/tmp.MDA334pGOw /sourcegraph
01:10:57         syntect_server | docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
01:10:57         syntect_server | See 'docker run --help'.
01:10:57         syntect_server | Terminating syntect_server
01:10:57                  nginx | Terminating nginx
01:10:57      zoekt-indexserver | Terminating zoekt-indexserver
01:10:57            lsif-server | Terminating lsif-server
01:10:57                grafana | Terminating grafana
01:10:57                symbols | /sourcegraph
01:10:57                symbols | Building /sourcegraph/libsqlite3-pcre.so... done
01:10:57                symbols | Building the /sourcegraph/.bin/symbols executable...
01:10:57             prometheus | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
01:10:57             prometheus | Terminating prometheus
01:10:57            lsif-worker | yarn run v1.19.1
01:10:57              gitserver | Terminating gitserver
01:10:57               searcher | Terminating searcher
01:10:57           github-proxy | Terminating github-proxy
01:10:58 management-console-web | Terminating management-console-web
01:10:58           query-runner | Terminating query-runner
01:10:58                symbols | Terminating symbols
01:10:58                    web | Terminating web
01:10:58     management-console | Terminating management-console
01:10:58               frontend | Failed to migrate the DB. Please contact support@sourcegraph.com for further assistance: Dirty database version 1528395601. Fix and force version.
01:10:58            lsif-worker | Terminating lsif-worker
01:10:58               frontend | Terminating frontend
01:10:58                  watch | Terminating watch
01:10:58        zoekt-webserver | Terminating zoekt-webserver
01:10:58                docsite | Terminating docsite
01:10:58           repo-updater | Terminating repo-updater
01:10:58               replacer | Terminating replacer
goreman: exit status 125
```

What's the recommended path forward for running a containerized version of the open source plan?

**Comment by unknwon** [comment]
>Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by slimsag** [comment]
Ah, I actually responded over on your tweet earlier: https://twitter.com/naturalwarren/status/1196968987759767552

Let me know if that doesn't work.

**Comment by naturalwarren** [comment]
> Do you have Docker running?

No, as mentioned in my original message I don't 😇. I was hoping not to have to run Docker in Docker.

> Ah, I actually responded over on your tweet earlier.
> 
> Let me know if that doesn't work.

Running `./dev/dev-sourcegraph-server.sh` at tag `v3.9.4`. 

I don't think it's producing Docker images. The script appears to invoke `cmd/server/build.sh` and outputs binaries in a temporary directory: 

`/var/folders/8s/gn_6097n1kgbrv19qs29fr8m0000gn/T/sgserver_XXXXXXX.CVwOjc1d`.

The [portion of the script](https://github.com/sourcegraph/sourcegraph/blob/2d749a0aab4d00a98261bee9c21021974381a160/cmd/server/build.sh#L66) that invokes `docker build` doesn't seem to run. Can't see the echo on line 66 in my terminal.

**Comment by naturalwarren** [comment]
Was able to fix the error in the output above by running `management-console/pre-build.sh` prior to running `./dev/dev-sourcegraph-server.sh`. Now Postgres is bombing in `server/Dockerfile`:

```bash
ERROR: unsatisfiable constraints:
  postgresql-12.1-r0:
    breaks: world[postgresql=11.5-r1]
  postgresql-contrib-12.1-r0:
    breaks: world[postgresql-contrib=11.5-r1]
The command '/bin/sh -c apk update && apk add --no-cache     'bash=5.0.0-r0' 'postgresql-contrib=11.5-r1' 'postgresql=11.5-r1'     'redis=3.2.12-r0' bind-tools ca-certificates git@edge     mailcap nginx openssh-client pcre su-exec tini nodejs-current=12.4.0-r0' returned a non-zero code: 2
+ cleanup
+ rm -rf /var/folders/8s/gn_6097n1kgbrv19qs29fr8m0000gn/T/sgserver_XXXXXXX.f2oNSkxM
       64.46 real        38.48 user        22.58 sys
```

**Comment by naturalwarren** [comment]
Bumped [these](https://github.com/sourcegraph/sourcegraph/blob/2d749a0aab4d00a98261bee9c21021974381a160/cmd/server/Dockerfile#L45) to 'postgresql-contrib=12.1-r0' 'postgresql=12.1-r0' to resolve the conflict. Image was produced and server could be started.

**Comment by slimsag** [comment]
> I was hoping not to have to run Docker in Docker.

You definitely don't need to run docker in docker.

> I don't think it's producing Docker images. The script appears to invoke cmd/server/build.sh and outputs binaries in a temporary directory:

the `build.sh` and `pre-build.sh` scripts aren't meant to be invoked directly, they produce the binaries into the tmp directory before packaging them up into the final docker image.

Just `./dev/dev-sourcegraph-server.sh` should be enough to produce the OSS image, but it is possible something has broken here recently. I'll see if I can take a look sometime soon.

> Bumped these to 'postgresql-contrib=12.1-r0' 'postgresql=12.1-r0' to resolve the conflict.

Yeah, this was fixed in `master` more recently, I think if you use the v3.10.0 tag this is fixed there.

**Comment by naturalwarren** [comment]
Was able to build and deploy. Closing this issue. Thanks! 🙌

**Comment by mipearson** [comment]
Reading through this - is it correct to say that these are the only instructions available for running the OSS version? 

And is it possible to turn off user authentication entirely?

**Comment by mipearson** [comment]
Confirmed that 
```
cmd/management-console/shared/main.go:133:48: undefined: assets.Assets
```
is still an issue on 3.10.0. Want me to raise a new issue?

**Comment by slimsag** [comment]
@mipearson Yes, docs here are insufficient currently I agree. I have filed issues for us to follow-up:

- Building enterprise and OSS images outside of CI is broken #6789
- Documentation for building OSS and enterprise images is missing #6790

Regarding turning off authentication entirely, let's continue that discussion in #6783 (I will follow up there soon)
